language: python
matrix:
        include:
                - python: 3.8.1
install:
        - pip install -r travis_requirements.txt
script: 
        - coverage run robot.py test --builtin
        - coverage xml
        - python-codacy-coverage -r coverage.xml
